plebiscito/config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'

  get 'votes/search'
  get "main/index"
  get "main/hola"
  get "main/votar"
  get "main/folleto"
  get "search/create"
  get "search/ocreate"
  get "search/ucreate"
  get "search/votar"
  get "statistic/salida"
  get "search/vcreate"
  get "search/getvotes"
  get "stats/salida"
  
  resources :places do
    resources :voters do
      get :votar
      get :notfound
    end
    get :asociado
  end
  resources :stats
  devise_for :users
  get 'principal/index'
  root "principal#index"
end

plebiscito/app/models/place.rb
class Place < ActiveRecord::Base
	has_many :voters
	validates :nombre, :ciudad, :direccion , :departamento, :presence => true
	validates :nombre, {:uniqueness => true}
end

plebiscito/app/models/stat.rb
class Stat < ActiveRecord::Base
end

plebiscito/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

plebiscito/app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :place, required: true
  validates :cedula, {:uniqueness => true}
end

plebiscito/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

plebiscito/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def hola
  	@saludo = "hola world"
  end

  def folleto
    @voter = Voter.find(params[:id])
    @voter.havotado = "si"
    @voter.save
    puts @voter
  end
end

plebiscito/app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all
	end

	def show
		@votante = "#{params[:votante]}"
		@place = Place.find(params[:id])
	end
	
	def new
		@place = Place.new
	end
	def edit
		@place = Place.find(params[:id])
	end
	def create
		@place = Place.new(place_params)
		
		if @place.save
			redirect_to @place
		else
			render 'new'
		end
	end
	
	def update
		@place = Place.find(params[:id])
  		
  		if @place.update(place_params)
    		redirect_to @place
  		else
    		render 'edit'
    	end	
	end

	def destroy
 		@place = Place.find(params[:id])
 		@place.destroy
 		redirect_to @place
	end

	private
		def place_params
			params.require(:place).permit(:nombre,:direccion,:ciudad,:departamento)
		
		end
end

plebiscito/app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  	
  end
end

plebiscito/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
  	palabra = "%#{params[:keyword]}%"
  	@places = Place.where("nombre LIKE ? OR ciudad LIKE ?",palabra,palabra)
  	#@voters = Voter.where("cedula LIKE ?",palabra,palabra)

  	respond_to do |format|
  		format.html { redirect_to "/main/index" }
  		format.json {  render json: @places}
  		format.js 
  	end
  end
  def ocreate
    palabra = "%#{params[:keyword]}%"
    #@places = Place.where("nombre LIKE ? OR ciudad LIKE ?",palabra,palabra)
    #@v = Voter.select("id").where("cedula LIKE ?",palabra)
    @voter = Voter.select("place_id,nombre").where("cedula LIKE ?",palabra)
    @i = 1
    #@places = Place.find(params[:place_id])
    #@place = Place.find(@v)

    respond_to do |format|
      format.html { redirect_to "/main/hola" }
      format.json {  render json: @voter}
      format.js 
    end
  end

  def votar
    $pid = "#{params[:pid]}"
  end

  def ucreate
    palabra = "%#{params[:keyword]}%"
    @voter = Voter.select("id,nombre,havotado").where("cedula LIKE ? AND place_id LIKE ?",palabra,$pid)
    
    if @voter.empty? 
      @voter = Voter.select("place_id,nombre").where("cedula LIKE ?",palabra)
      @i = 3
    else
      @i = 2
    end
    respond_to do |format|
      format.html { redirect_to "/main/votar" }
      format.json {  render json: @voter}
      format.js 
    end
  end
  
  def getvotes
    palabra = "#{params[:option]}"
    @idm = Place.select("id").where("nombre = ?",palabra)
    @idm = @idm.to_a
    puts @idm
    @stats = Stat.where("idmesa = ?",@idm)
    @yesm = 0
    @nom = 0
    @stats.each do |stat|
      @yesm = @yesm + stat.vote_yes
      @nom = @nom + stat.vote_no
    end
    @numvotes = [@yesm,@nom]
    #puts @numvotes

      respond_to do |format|
          format.html { redirect_to "/stats/index" }
          format.json { render json: @numvotes}
          format.js 
      end
  end
end

plebiscito/app/controllers/statistic_controller.rb
class StatisticController < ApplicationController
	def index
		
	end

	def salida
		vote1 = "#{params[:voto1]}"
		vote2 = "#{params[:voto2]}"
		@voto = Stat.create(vote_yes: vote1, vote_no: vote2, idmesa: $pid)
				
	end
end

plebiscito/app/controllers/stats_controller.rb
class StatsController < ApplicationController
	def index
		@stats = Stat.all
		@places = Place.all
	end
	def show
		
	end
	def salida
		vote1 = "#{params[:voto1]}"
		vote2 = "#{params[:voto2]}"
		@voto = Stat.create(vote_yes: vote1, vote_no: vote2, idmesa: $pid)
				
	end
end

plebiscito/app/controllers/voters_controller.rb
class VotersController < ApplicationController
	def create
    	@place = Place.find(params[:place_id])
    	@voter = @place.voters.create(voter_params)
    	@voter.ciudad = @place.ciudad
  		@voter.departamento = @place.departamento
  		@voter.havotado = "false"
    	redirect_to place_voters_path(@place)
  end

  def index
		@voter = Voter.new
		@place = Place.find(params[:place_id])
	end

 	def new
 		@place = Place.find(params[:place_id])
 	end

  def update
    @voter = Voter.find(params[:id])
      
      if @voter.update(voter_params)
        redirect_to @voter
      else
        render 'edit'
      end 
  end

  	private
    	def voter_params
      	params.require(:voter).permit(:cedula, :nombre, :ciudad, :departamento, :havotado)
    	end
end

plebiscito/app/helpers/application_helper.rb
module ApplicationHelper
end

plebiscito/app/helpers/main_helper.rb
module MainHelper
end

plebiscito/app/helpers/places_helper.rb
module PlacesHelper
end

plebiscito/app/helpers/principal_helper.rb
module PrincipalHelper
end

plebiscito/app/helpers/search_helper.rb
module SearchHelper
end

plebiscito/app/helpers/statistic_helper.rb
module StatisticHelper
end

plebiscito/app/helpers/voters_helper.rb
module VotersHelper
end

plebiscito/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plebiscito</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag "https://www.google.com/jsapi" %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <% if user_signed_in? %>
	  <li>
	  	<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
	  </li>
	  <%else%>
	  <li>
	  	<%= link_to "Admin", new_user_session_path %>
	  </li>
	  <li>
	  	<%= link_to "Home", root_path %>
	  </li>
  <%end%>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

plebiscito/app/views/main/folleto.html.erb
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com") %>
<h1>Cartilla de votación</h1>
<h2>¿Apoya usted el acuerdo final para la terminación del conflicto y la construcción de una paz estable y duradera?</h2>
<strong><h1><%= link_to 'SI',stats_salida_path(:voto1 => 1, :voto2 => 0), data: { confirm: "Su opción es: SI \n ¿Está seguro?" }%></h1></strong> 
<strong><h1><%= link_to 'NO',stats_salida_path(:voto1 => 0, :voto2 => 1), data: { confirm: "Su opción es: NO \n ¿Está seguro?" }%></h1></strong>
<%end%>

plebiscito/app/views/main/hola.html.erb
<h1><%= @saludo %></h1>
<%= form_tag "/search/ocreate", method: :get, remote:  true, id:"search-form" do %>
	<%= text_field_tag :keyword, nil, placeholder: "Buscar cedula" %>
	<%= content_tag :button, type: :submit do %>
	buscar
	<%end%>
<%end%>

<div id="resultados">
	

</div>

plebiscito/app/views/main/index.html.erb
<%= form_tag "/search/create", method: :get, remote:  true, id:"search-form" do %>
	<%= text_field_tag :keyword, nil, placeholder: "Buscar puesto" %>
	<%= content_tag :button, type: :submit do %>
	buscar
	<%end%>
<%end%>

<div id="resultados">
	

</div>

plebiscito/app/views/places/_place.html.erb
<div>
<strong><%= place.nombre %></strong>
	<%= place.direccion %>
	<%= place.ciudad %>
	-
	<%= link_to "Ver", place , style:"color:blue;text-decoration:underline;" %>
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
	<%= link_to "Asociar", search_votar_path(:action => "ucreate", :pid => place.id) , data: { confirm: '¿Estás seguro?' }, style:"color:blue;text-decoration:underline;" %>
<%end%>
</div>

plebiscito/app/views/places/edit.html.erb
<h1>Modificar Puesto de Votación</h1>
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
    <%= form_for :place, url: place_path(@place), method: :patch do |f| %>
     
      <% if @place.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@place.errors.count, "error") %> han impedido que el puesto sea registrado:
        </h2>
          <ul>
            <% @place.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <p>
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre %>
      </p>
     
      <p>
        <%= f.label :direccion %><br>
        <%= f.text_field :direccion %>
      </p>

      <p>
        <%= f.label :ciudad %><br>
        <%= f.text_field :ciudad %>
      </p>

      <p>
        <%= f.label :departamento %><br>
        <%= f.text_field :departamento %>
      </p>
     
      <p>
        <%= f.submit 'Registrar Puesto' %>
      </p>
    <% end %>
  <%else%>
    <h1>Acceso denegado</h1>
<% end %>
 
<%= link_to 'Volver', place_path %>

plebiscito/app/views/places/index.html.erb
<h1>Puestos de Votación Registrados</h1>
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
<%= link_to 'Nuevo Puesto', new_place_path %>
<%= link_to 'Buscar Puestos de Votación', '/main/index' %>
<table>
  <tr>
    <th>Nombre</th>
    <th>Dirección</th>
    <th>Ciudad</th>
    <th>Departamento</th>
    <th colspan="2"></th>
  </tr>
 
  <% @places.each do |place| %>

    <tr>
      <td><%= place.nombre %></td>
      <td><%= place.direccion %></td>
      <td><%= place.ciudad %></td>
      <td><%= place.departamento %></td>
      <td><%= link_to 'Ver', place_path(place) %></td>
      <td><%= link_to 'Editar', edit_place_path(place) %></td>  
      <td><%= link_to 'Borrar', place_path(place), method: :delete, data: { confirm: '¿Estás seguro?' } %></td>   
    </tr>
  <% end %>
</table>
<%else%>
      <%= link_to 'Buscar Puestos de Votación', '/main/index' %>
  <table>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Ciudad</th>
      <th>Departamento</th>
      <th colspan="2"></th>
    </tr>
   
    <% @places.each do |place| %>

      <tr>
        <td><%= place.nombre %></td>
        <td><%= place.direccion %></td>
        <td><%= place.ciudad %></td>
        <td><%= place.departamento %></td>
        <td><%= link_to 'Ver', place_path(place) %></td>
      </tr>
    <%end%>
        </table>
<% end %>

plebiscito/app/views/places/new.html.erb
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
 <%= form_for :place, url: places_path do |f| %>

  <% if @place.errors.any? %>
    <div id="error_explanation">
    <h2>
        <%= pluralize(@place.errors.count, "error") %> han impedido que el puesto sea registrado:
    </h2>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label(:nombre,"Nombre del Puesto") %><br>
    <%= f.text_field :nombre %>
  </p>
 
  <p>
    <%= f.label(:direccion, :value => "Dirección") %><br>
    <%= f.text_field :direccion %>
  </p>
  <p>
    <%= f.label(:ciudad,"Ciudad") %><br>
    <%= f.text_field :ciudad %>
  </p>
  <p>
    <%= f.label(:departamento,"Departamento") %><br>
    <%= f.text_field :departamento %>
  </p>
  <p>
    <%= f.submit 'Registrar Puesto' %>
  </p>
<% end %>
<%= link_to 'Volver', places_path %>
<%end%>

plebiscito/app/views/places/show.html.erb
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
    <p>
      <strong>Nombre:</strong>
      <%= @place.nombre %>
    </p>
     
    <p>
      <strong>Dirección:</strong>
      <%= @place.direccion %>
    </p>
    <p>
      <strong>Ciudad:</strong>
      <%= @place.ciudad %>
    </p>
    <p>
      <strong>Departamento:</strong>
      <%= @place.departamento %>
    </p>
    <%if @votante == 'no' %>
    	<%= link_to 'Votantes', place_voters_path(@place) %>
    	<%= link_to 'Editar', edit_place_path(@place) %>
    <% end %>
    <%= link_to 'Votantes', place_voters_path(@place) %>
    <%= link_to 'Editar', edit_place_path(@place) %>
<%else%>
    <p>
      <strong>Nombre:</strong>
      <%= @place.nombre %>
    </p>
     
    <p>
      <strong>Dirección:</strong>
      <%= @place.direccion %>
    </p>
    <p>
      <strong>Ciudad:</strong>
      <%= @place.ciudad %>
    </p>
    <p>
      <strong>Departamento:</strong>
      <%= @place.departamento %>
    </p>
<% end %>
<%= link_to 'Volver', places_path %>

plebiscito/app/views/principal/index.html.erb
<h1>Votaciones Plebiscito</h1>
<p>Find me in app/views/principal/index.html.erb</p>
<%= link_to 'Puestos de votaciones', places_path %>
<%= link_to 'Buscar mi lugar de votación', '/main/hola' %>

plebiscito/app/views/search/create.html.erb
$("#resultados").html("<%= j render @places %>")

plebiscito/app/views/search/getvotes.html.erb
$("#resultados2").html("<%= j render "/stats/stat" %>")

plebiscito/app/views/search/ocreate.html.erb
$("#resultados").html("<%= j render @voter %>")

plebiscito/app/views/search/ucreate.html.erb
$("#resultados1").html("<%= j render @voter %>")

plebiscito/app/views/search/votar.html.erb
<h1>Aquí es donde van a votar</h1>

<%= form_tag "/search/ucreate", method: :get, remote:  true, id:"search-form" do %>
	<%= text_field_tag :keyword, nil, placeholder: "Buscar cedula" %>
	<%= content_tag :button, type: :submit do %>
	buscar
	<%end%>
<%end%>

<div id="resultados1">
	

</div>

plebiscito/app/views/stats/_stat.html.erb
<div>

	<p>El número de votos por el sí en este puesto es: <span id="nyes"><%= @yesm = @numvotes[0] %></span></p>
	<p>El número de votos por el no en este puesto es: <span id="nno"><%= @nom = @numvotes[1] %></span></p>	
	<div>
	<% if @yesm == 0 and @nom == 0 %>
	<%= pie_chart({"Sí [%]"=> 0, "No [%]"=> 0 }) %>
	<% else %>
	<%= pie_chart({"Sí [%]"=>100*@yesm/(@yesm+@nom), "No [%]"=>100*@nom/(@yesm+@nom)}) %>
	<% end %>
	</div>
</div>

plebiscito/app/views/stats/index.html.erb
<h1 >Así van las votaciones</h1>
<%@yes = 0%>
<%@no = 0%>
<% @stats.each do |stat| %>

	<% @yes = @yes + stat.vote_yes %>
	<% @no = @no + stat.vote_no %>
<% end %>
<h4><strong>Votos por el sí: </strong>
<% if @yes == 0 and @no == 0 %>
<%= 0 %>
<% else %>
<%= 100*@yes/(@yes+@no) %>
<% end %>
%</h4>
<h4><strong>Votos por el no: </strong>
<% if @yes == 0 and @no == 0 %>
<%= 0 %>
<% else %>
<%= 100*@no/(@yes+@no) %>
<% end %>
%</h4>
<!-- Esto es para obtener las ids de las mesas en las que se ha votado en @idm-->
<% @idm = Array.new %>
<% @idm[0] = 0 %> 
<% @a = 1 %>
<% @stats.each do |stat| %>
    <% @i=0 %>
	<% @idm.each do |id| %>
  		<% if id == stat.idmesa %>
    		<% @i=1 %>
    	<% end %>
   	<% end %>
   	<% if @i == 0 %>
    	<% @idm[@a] = stat.idmesa %>
    	<% @a = @a + 1 %>
    <% end %> 
<% end %>
<%@idm = @idm[1..@idm.length]%>
<p>Seleccione el puesto de votación del que desea ver estadisticas </p>
<%= form_tag "/search/getvotes", method: :get, remote:  true, id:"select-form" do %>
	<%= select_tag :option, options_for_select(@places.collect{ |u| [u.nombre]}), :selected => :option %>
	<%= content_tag :button, type: :submit do %>
	buscar
	<%end%>
<%end%>

<div id="resultados2">
</div>

plebiscito/app/views/stats/salida.html.erb
<strong><h1>¡Felicidades por haber ejercido su derecho al voto!</h1></strong>
<%= link_to 'Nuevo Votante',search_votar_path(:pid => $pid )%>

plebiscito/app/views/voters/_voter.html.erb
<div>
<% if @i==1 %>
	<strong><%= voter.nombre %></strong>
	<td><%= link_to 'Ver sitio de votación', place_path(voter.place_id, :votante => 'si') %></td>
<% elsif @i==2%>
	<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
		<strong><%= voter.nombre %></strong>
		<% if voter.havotado == 'si'%>
			<td>El ciudadano ya votó</td>
		<% else %>
			<td><%= link_to 'Votar', main_folleto_path(:id => voter.id) %></td>
		<% end %>
	<%end%>
<% else%>
	<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
		<strong>El ciudadano </strong>
		<strong><%= voter.nombre %></strong>
		<strong> no se encuentra inscrito en este puesto de votación</strong>
		<td><%= link_to 'Ver sitio de votación', place_path(voter.place_id, :votante => 'si') %></td>
	<%end%>
<% end %>
</div>

plebiscito/app/views/voters/index.html.erb
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com") %>
<h1>Votantes<h1>

<% @place.voters.each do |voter| %>
	  <p>
	    <strong>Votante: </strong>
	    <%= voter.nombre %>
	  </p>
	 
	  <p>
	    <strong>Cedula: </strong>
	    <%= voter.cedula %>
	  </p>
<% end %>
<%= link_to 'Nuevo votante', new_place_voter_path(@place) %>
<%end%>
<%= link_to 'Volver', place_path(@place[:id]) %>

plebiscito/app/views/voters/new.html.erb
<% if user_signed_in? && (current_user.email == "dayanm@uninorte.com" || current_user.email == "hector@uninorte.com" || current_user.email == "julian@uninorte.com" ) %>
<h1>Registro de cedulas</h1>

<h2>Agregar un votante:</h2>
<p>Se registrará el votante en el puesto <%=@place.nombre%>, en <%=@place.ciudad%>,<%=@place.departamento%></p>
<%= form_for([@place, @place.voters.build]) do |f| %>
  <p>
    <%= f.label(:nombre,"Nombre y Apellidos") %><br>
    <%= f.text_field :nombre %>
  </p>
  <p>
    <%= f.label(:cedula,"Cedula") %><br>
    <%= f.text_field :cedula %>
  </p>
  <p>
    <%= f.submit 'Registrar Votante'%>
  </p>

<% end %>
<%end%>

plebiscito/app/views/voters/notfound.html.erb
<h1> No se ha encontrado la cedula </h1>
<%= link_to 'Volver', place_asociado_path(Place.find(params[:place_id])) %>

plebiscito/app/views/voters/votar.html.erb
<h1>Hola, <%= Voter.find(params[:voter_id]).nombre %> </h1>